### ISSUE TITLE
Allow nacking messages

### ISSUE THREAD

**Issue by Ascalogan** [twindagger/magicbus#14]
Currently consumer adds listener for 'nack' event, but there is no way to emit this event in right place. It can only be used by custom middleware which knows nothing about handler response. Handler does not receive actions object (consumer passes it to subscriber which ignores it).

**Comment by twindagger** [comment]
I added support along with a test in https://github.com/twindagger/magicbus/commit/bada0c15e1267cb064a3ea172449ca8d111beac3 

It should be published soon as version 4.1.0

In the future I plan on replacing the parameters passed to handling functions with a "Consumption Context" object that will contain the same data along with resolution methods like ack, nack, etc.

**Comment by twindagger** [comment]
Let me know if this meets your needs so I can close the issue.

**Comment by Ascalogan** [comment]
Yes, it looks fine. Thanks for fast react :)
